spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/prod_db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate 사용
    show-sql: false
    properties:
      hibernate:
        format_sql: false
