spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/property_service_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true   # API 문서 활성화
  swagger-ui:
    enabled: true   # Swagger UI 활성화
    path: /swagger-ui.html  # Swagger UI 경로
